### ISSUE TITLE
General bug, probably due to new Compose Versions 

### ISSUE THREAD

**Issue by aenadgrleey** [AndroidPoet/Dropdown#5]
**Please complete the following information:**
- Library Version 1.0.1 
- Affected Device(s) I guess it affects every device
 
**Describe the Bug:**

Instead of having a beautiful dropdown, I have very long logcat message that contains this: 
The same happens while trying to load preview app
```
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Lt0/Modifier;Lo7/Function1;Lt0/Alignment;Lo7/Function4;Li0/Composer;II)V in class Lo/l; or its super classes (declaration of 'o.l' appears in base.apk)
                                                                                                    	at a5.h.a(Unknown Source:204)
                                                                                                    	at a5.h.S(Unknown Source:10)
                                                                                                    	at p0.b.a(Unknown Source:50)
                                                                                                    	at p0.b.S(Unknown Source:8)
                                                                                                    	at q.t.a(Unknown Source:395)
                                                                                                    	at q.t.V(Unknown Source:125)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at c0.z0.a(Unknown Source:273)
                                                                                                    	at c0.z0.V(Unknown Source:16)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at v4.f.a(Unknown Source:182)
                                                                                                    	at g1.c.p(Unknown Source:436)
                                                                                                    	at c0.v.a(Unknown Source:646)
                                                                                                    	at o.h0.a(Unknown Source:87)
                                                                                                    	at o.h0.V(Unknown Source:28)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at g2.c.a(Unknown Source:570)
                                                                                                    	at g2.c.V(Unknown Source:52)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at r.e0.b(Unknown Source:253)
                                                                                                    	at r.e0.V(Unknown Source:46)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at g2.v.a(Unknown Source:17)
                                                                                                    	at u.t0.a(Unknown Source:70)
                                                                                                    	at u.t0.V(Unknown Source:85)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at v4.f.a(Unknown Source:182)
                                                                                                    	at androidx.compose.ui.platform.g1.a(Unknown Source:344)
                                                                                                    	at q.u.a(Unknown Source:167)
                                                                                                    	at q.u.V(Unknown Source:53)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at v4.f.a(Unknown Source:182)
                                                                                                    	at androidx.compose.ui.platform.p0.a(Unknown Source:549)
                                                                                                    	at androidx.compose.ui.platform.f3.a(Unknown Source:33)
                                                                                                    	at androidx.compose.ui.platform.f3.V(Unknown Source:16)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at v4.f.a(Unknown Source:182)
                                                                                                    	at androidx.compose.ui.platform.f3.a(Unknown Source:178)
                                                                                                    	at androidx.compose.ui.platform.f3.V(Unknown Source:28)
                                                                                                    	at p0.b.V(Unknown Source:58)
                                                                                                    	at q.a2.a(Unknown Source:325)
                                                                                                    	at q.a2.p(Unknown Source:27)
                                                                                                    	at v4.f.C(Unknown Source:43)
                                                                                                    	at i0.y.q(Unknown Source:128)
                                                                                                    	at i0.y.j(Unknown Source:13)
                                                                                                    	at i0.d0.m(Unknown Source:17)
                                                                                                    	at i0.a2.a(Unknown Source:38)
                                                                                                    	at i0.k.a(Unknown Source:9)
                                                                                                    	at i0.k.a(Unknown Source:9)
                                                                                                    	at i0.d0.e(Unknown Source:10)
                                                                                                    	at androidx.compose.ui.platform.g3.d0(Unknown Source:101)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:11)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.e(Unknown Source:13)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.c(Unknown Source:18)
                                                                                                    	at androidx.lifecycle.x.a(Unknown Source:22)
                                                                                                    	at androidx.lifecycle.y.a(Unknown Source:106)
                                                                                                    	at androidx.compose.ui.platform.g3.d0(Unknown Source:72)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:109)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:18347)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:696)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
**Expected Behavior:**

Just one awesome dropdown......

**Comment by Redwid** [comment]
+1 the same issue for me after migrating from
androidx.compose.animation:animation-core:1.2.1 -> 1.5.0

**Comment by michaellinder1995** [comment]
+1 after upgraded to 1.5.0. 
The lib is nice. So would be great, if you could fix it

**Comment by AndroidPoet** [comment]
The library has been migrated to Compose multiplatform, and the issue have also been fixed.
